version: '3'

services:
  app:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - alura-net
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/alura?allowPublicKeyRetrieval=true&useSSL=false
      - spring.datasource.username=root
      - spring.datasource.password=alura
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .m2:/root/.m2
  db:
    image: mysql:8.0.36-debian
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=alura
      - MYSQL_ROOT_PASSWORD=alura
      - MYSQL_USER=alura
      - MYSQL_PASSWORD=alura
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - alura-net
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      retries: 10
      interval: 3s
      timeout: 30s

volumes:
  mysql:

networks:
  alura-net: